/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements Serializable {

    private static final long serialVersionUID = -991888348;

    private Integer id;
    private String  code;
    private String  langCode;
    private String  nane;

    public Country() {}

    public Country(Country value) {
        this.id = value.id;
        this.code = value.code;
        this.langCode = value.langCode;
        this.nane = value.nane;
    }

    public Country(
        Integer id,
        String  code,
        String  langCode,
        String  nane
    ) {
        this.id = id;
        this.code = code;
        this.langCode = langCode;
        this.nane = nane;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLangCode() {
        return this.langCode;
    }

    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }

    public String getNane() {
        return this.nane;
    }

    public void setNane(String nane) {
        this.nane = nane;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(langCode);
        sb.append(", ").append(nane);

        sb.append(")");
        return sb.toString();
    }
}
