/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product implements Serializable {

    private static final long serialVersionUID = -1801536439;

    private Integer id;
    private String  content;
    private String  title;
    private Integer sellerId;
    private Integer pandp;
    private Integer price;

    public Product() {}

    public Product(Product value) {
        this.id = value.id;
        this.content = value.content;
        this.title = value.title;
        this.sellerId = value.sellerId;
        this.pandp = value.pandp;
        this.price = value.price;
    }

    public Product(
        Integer id,
        String  content,
        String  title,
        Integer sellerId,
        Integer pandp,
        Integer price
    ) {
        this.id = id;
        this.content = content;
        this.title = title;
        this.sellerId = sellerId;
        this.pandp = pandp;
        this.price = price;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getSellerId() {
        return this.sellerId;
    }

    public void setSellerId(Integer sellerId) {
        this.sellerId = sellerId;
    }

    public Integer getPandp() {
        return this.pandp;
    }

    public void setPandp(Integer pandp) {
        this.pandp = pandp;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Product (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(title);
        sb.append(", ").append(sellerId);
        sb.append(", ").append(pandp);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
