/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestDummy implements Serializable {

    private static final long serialVersionUID = -879544743;

    private Integer id;
    private String  name;
    private String  email;

    public TestDummy() {}

    public TestDummy(TestDummy value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
    }

    public TestDummy(
        Integer id,
        String  name,
        String  email
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestDummy (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
