/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1481333064;

    private Integer id;
    private String  account;
    private String  countryCode;
    private String  name;
    private Integer pasword;
    private String  email;
    private String  language;
    private Integer password;
    private Integer profileId;
    private Integer locationId;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.account = value.account;
        this.countryCode = value.countryCode;
        this.name = value.name;
        this.pasword = value.pasword;
        this.email = value.email;
        this.language = value.language;
        this.password = value.password;
        this.profileId = value.profileId;
        this.locationId = value.locationId;
    }

    public User(
        Integer id,
        String  account,
        String  countryCode,
        String  name,
        Integer pasword,
        String  email,
        String  language,
        Integer password,
        Integer profileId,
        Integer locationId
    ) {
        this.id = id;
        this.account = account;
        this.countryCode = countryCode;
        this.name = name;
        this.pasword = pasword;
        this.email = email;
        this.language = language;
        this.password = password;
        this.profileId = profileId;
        this.locationId = locationId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPasword() {
        return this.pasword;
    }

    public void setPasword(Integer pasword) {
        this.pasword = pasword;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Integer getPassword() {
        return this.password;
    }

    public void setPassword(Integer password) {
        this.password = password;
    }

    public Integer getProfileId() {
        return this.profileId;
    }

    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(account);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(name);
        sb.append(", ").append(pasword);
        sb.append(", ").append(email);
        sb.append(", ").append(language);
        sb.append(", ").append(password);
        sb.append(", ").append(profileId);
        sb.append(", ").append(locationId);

        sb.append(")");
        return sb.toString();
    }
}
