/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.CategoryLevel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryLevelRecord extends UpdatableRecordImpl<CategoryLevelRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = -694488851;

    /**
     * Setter for <code>magpie.category_level.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.category_level.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.category_level.level1</code>.
     */
    public void setLevel1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.category_level.level1</code>.
     */
    public String getLevel1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.category_level.level2</code>.
     */
    public void setLevel2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.category_level.level2</code>.
     */
    public String getLevel2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.category_level.level3</code>.
     */
    public void setLevel3(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.category_level.level3</code>.
     */
    public String getLevel3() {
        return (String) get(3);
    }

    /**
     * Setter for <code>magpie.category_level.level3_id</code>.
     */
    public void setLevel3Id(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.category_level.level3_id</code>.
     */
    public Integer getLevel3Id() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CategoryLevel.CATEGORY_LEVEL.ID;
    }

    @Override
    public Field<String> field2() {
        return CategoryLevel.CATEGORY_LEVEL.LEVEL1;
    }

    @Override
    public Field<String> field3() {
        return CategoryLevel.CATEGORY_LEVEL.LEVEL2;
    }

    @Override
    public Field<String> field4() {
        return CategoryLevel.CATEGORY_LEVEL.LEVEL3;
    }

    @Override
    public Field<Integer> field5() {
        return CategoryLevel.CATEGORY_LEVEL.LEVEL3_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLevel1();
    }

    @Override
    public String component3() {
        return getLevel2();
    }

    @Override
    public String component4() {
        return getLevel3();
    }

    @Override
    public Integer component5() {
        return getLevel3Id();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLevel1();
    }

    @Override
    public String value3() {
        return getLevel2();
    }

    @Override
    public String value4() {
        return getLevel3();
    }

    @Override
    public Integer value5() {
        return getLevel3Id();
    }

    @Override
    public CategoryLevelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CategoryLevelRecord value2(String value) {
        setLevel1(value);
        return this;
    }

    @Override
    public CategoryLevelRecord value3(String value) {
        setLevel2(value);
        return this;
    }

    @Override
    public CategoryLevelRecord value4(String value) {
        setLevel3(value);
        return this;
    }

    @Override
    public CategoryLevelRecord value5(Integer value) {
        setLevel3Id(value);
        return this;
    }

    @Override
    public CategoryLevelRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryLevelRecord
     */
    public CategoryLevelRecord() {
        super(CategoryLevel.CATEGORY_LEVEL);
    }

    /**
     * Create a detached, initialised CategoryLevelRecord
     */
    public CategoryLevelRecord(Integer id, String level1, String level2, String level3, Integer level3Id) {
        super(CategoryLevel.CATEGORY_LEVEL);

        set(0, id);
        set(1, level1);
        set(2, level2);
        set(3, level3);
        set(4, level3Id);
    }
}
