/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.Country;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryRecord extends UpdatableRecordImpl<CountryRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 550427169;

    /**
     * Setter for <code>magpie.country.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.country.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.country.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.country.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.country.lang_code</code>.
     */
    public void setLangCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.country.lang_code</code>.
     */
    public String getLangCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.country.nane</code>.
     */
    public void setNane(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.country.nane</code>.
     */
    public String getNane() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Country.COUNTRY.ID;
    }

    @Override
    public Field<String> field2() {
        return Country.COUNTRY.CODE;
    }

    @Override
    public Field<String> field3() {
        return Country.COUNTRY.LANG_CODE;
    }

    @Override
    public Field<String> field4() {
        return Country.COUNTRY.NANE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getLangCode();
    }

    @Override
    public String component4() {
        return getNane();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getLangCode();
    }

    @Override
    public String value4() {
        return getNane();
    }

    @Override
    public CountryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CountryRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CountryRecord value3(String value) {
        setLangCode(value);
        return this;
    }

    @Override
    public CountryRecord value4(String value) {
        setNane(value);
        return this;
    }

    @Override
    public CountryRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CountryRecord
     */
    public CountryRecord() {
        super(Country.COUNTRY);
    }

    /**
     * Create a detached, initialised CountryRecord
     */
    public CountryRecord(Integer id, String code, String langCode, String nane) {
        super(Country.COUNTRY);

        set(0, id);
        set(1, code);
        set(2, langCode);
        set(3, nane);
    }
}
