/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.Item;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record10<Integer, String, String, Integer, String, Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = -107281451;

    /**
     * Setter for <code>magpie.item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.item.currency</code>.
     */
    public void setCurrency(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.item.currency</code>.
     */
    public String getCurrency() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.item.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.item.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>magpie.item.nego_fg</code>.
     */
    public void setNegoFg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.item.nego_fg</code>.
     */
    public String getNegoFg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>magpie.item.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>magpie.item.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>magpie.item.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>magpie.item.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>magpie.item.title</code>.
     */
    public void setTitle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>magpie.item.title</code>.
     */
    public String getTitle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>magpie.item.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>magpie.item.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>magpie.item.seller_id</code>.
     */
    public void setSellerId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>magpie.item.seller_id</code>.
     */
    public Integer getSellerId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, String, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Item.ITEM.ID;
    }

    @Override
    public Field<String> field2() {
        return Item.ITEM.CURRENCY;
    }

    @Override
    public Field<String> field3() {
        return Item.ITEM.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return Item.ITEM.LOCATION_ID;
    }

    @Override
    public Field<String> field5() {
        return Item.ITEM.NEGO_FG;
    }

    @Override
    public Field<Integer> field6() {
        return Item.ITEM.PRICE;
    }

    @Override
    public Field<String> field7() {
        return Item.ITEM.STATUS;
    }

    @Override
    public Field<String> field8() {
        return Item.ITEM.TITLE;
    }

    @Override
    public Field<Integer> field9() {
        return Item.ITEM.CATEGORY_ID;
    }

    @Override
    public Field<Integer> field10() {
        return Item.ITEM.SELLER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCurrency();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getLocationId();
    }

    @Override
    public String component5() {
        return getNegoFg();
    }

    @Override
    public Integer component6() {
        return getPrice();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getTitle();
    }

    @Override
    public Integer component9() {
        return getCategoryId();
    }

    @Override
    public Integer component10() {
        return getSellerId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCurrency();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getLocationId();
    }

    @Override
    public String value5() {
        return getNegoFg();
    }

    @Override
    public Integer value6() {
        return getPrice();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getTitle();
    }

    @Override
    public Integer value9() {
        return getCategoryId();
    }

    @Override
    public Integer value10() {
        return getSellerId();
    }

    @Override
    public ItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ItemRecord value2(String value) {
        setCurrency(value);
        return this;
    }

    @Override
    public ItemRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ItemRecord value4(Integer value) {
        setLocationId(value);
        return this;
    }

    @Override
    public ItemRecord value5(String value) {
        setNegoFg(value);
        return this;
    }

    @Override
    public ItemRecord value6(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public ItemRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ItemRecord value8(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ItemRecord value9(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public ItemRecord value10(Integer value) {
        setSellerId(value);
        return this;
    }

    @Override
    public ItemRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7, String value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer id, String currency, String description, Integer locationId, String negoFg, Integer price, String status, String title, Integer categoryId, Integer sellerId) {
        super(Item.ITEM);

        set(0, id);
        set(1, currency);
        set(2, description);
        set(3, locationId);
        set(4, negoFg);
        set(5, price);
        set(6, status);
        set(7, title);
        set(8, categoryId);
        set(9, sellerId);
    }
}
