/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.Message;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record5<Integer, String, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 1169903327;

    /**
     * Setter for <code>magpie.message.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.message.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.message.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.message.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.message.sent_at</code>.
     */
    public void setSentAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.message.sent_at</code>.
     */
    public Timestamp getSentAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>magpie.message.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.message.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>magpie.message.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.message.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Timestamp, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Timestamp, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Message.MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.CONTENT;
    }

    @Override
    public Field<Timestamp> field3() {
        return Message.MESSAGE.SENT_AT;
    }

    @Override
    public Field<Integer> field4() {
        return Message.MESSAGE.ITEM_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Message.MESSAGE.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Timestamp component3() {
        return getSentAt();
    }

    @Override
    public Integer component4() {
        return getItemId();
    }

    @Override
    public Integer component5() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public Timestamp value3() {
        return getSentAt();
    }

    @Override
    public Integer value4() {
        return getItemId();
    }

    @Override
    public Integer value5() {
        return getUserId();
    }

    @Override
    public MessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public MessageRecord value3(Timestamp value) {
        setSentAt(value);
        return this;
    }

    @Override
    public MessageRecord value4(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public MessageRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public MessageRecord values(Integer value1, String value2, Timestamp value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(Integer id, String content, Timestamp sentAt, Integer itemId, Integer userId) {
        super(Message.MESSAGE);

        set(0, id);
        set(1, content);
        set(2, sentAt);
        set(3, itemId);
        set(4, userId);
    }
}
