/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.Product;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record6<Integer, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1476719523;

    /**
     * Setter for <code>magpie.product.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.product.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.product.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.product.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.product.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.product.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.product.seller_id</code>.
     */
    public void setSellerId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.product.seller_id</code>.
     */
    public Integer getSellerId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>magpie.product.pandp</code>.
     */
    public void setPandp(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.product.pandp</code>.
     */
    public Integer getPandp() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>magpie.product.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>magpie.product.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.CONTENT;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.TITLE;
    }

    @Override
    public Field<Integer> field4() {
        return Product.PRODUCT.SELLER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Product.PRODUCT.PANDP;
    }

    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.PRICE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Integer component4() {
        return getSellerId();
    }

    @Override
    public Integer component5() {
        return getPandp();
    }

    @Override
    public Integer component6() {
        return getPrice();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public Integer value4() {
        return getSellerId();
    }

    @Override
    public Integer value5() {
        return getPandp();
    }

    @Override
    public Integer value6() {
        return getPrice();
    }

    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ProductRecord value4(Integer value) {
        setSellerId(value);
        return this;
    }

    @Override
    public ProductRecord value5(Integer value) {
        setPandp(value);
        return this;
    }

    @Override
    public ProductRecord value6(Integer value) {
        setPrice(value);
        return this;
    }

    @Override
    public ProductRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String content, String title, Integer sellerId, Integer pandp, Integer price) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, content);
        set(2, title);
        set(3, sellerId);
        set(4, pandp);
        set(5, price);
    }
}
