/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.ProfileImageFile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileImageFileRecord extends UpdatableRecordImpl<ProfileImageFileRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = -1726864277;

    /**
     * Setter for <code>magpie.profile_image_file.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.profile_image_file.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.profile_image_file.file_name</code>.
     */
    public void setFileName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.profile_image_file.file_name</code>.
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.profile_image_file.file_url</code>.
     */
    public void setFileUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.profile_image_file.file_url</code>.
     */
    public String getFileUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.profile_image_file.profile_id</code>.
     */
    public void setProfileId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.profile_image_file.profile_id</code>.
     */
    public Integer getProfileId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProfileImageFile.PROFILE_IMAGE_FILE.ID;
    }

    @Override
    public Field<String> field2() {
        return ProfileImageFile.PROFILE_IMAGE_FILE.FILE_NAME;
    }

    @Override
    public Field<String> field3() {
        return ProfileImageFile.PROFILE_IMAGE_FILE.FILE_URL;
    }

    @Override
    public Field<Integer> field4() {
        return ProfileImageFile.PROFILE_IMAGE_FILE.PROFILE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFileName();
    }

    @Override
    public String component3() {
        return getFileUrl();
    }

    @Override
    public Integer component4() {
        return getProfileId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFileName();
    }

    @Override
    public String value3() {
        return getFileUrl();
    }

    @Override
    public Integer value4() {
        return getProfileId();
    }

    @Override
    public ProfileImageFileRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProfileImageFileRecord value2(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public ProfileImageFileRecord value3(String value) {
        setFileUrl(value);
        return this;
    }

    @Override
    public ProfileImageFileRecord value4(Integer value) {
        setProfileId(value);
        return this;
    }

    @Override
    public ProfileImageFileRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileImageFileRecord
     */
    public ProfileImageFileRecord() {
        super(ProfileImageFile.PROFILE_IMAGE_FILE);
    }

    /**
     * Create a detached, initialised ProfileImageFileRecord
     */
    public ProfileImageFileRecord(Integer id, String fileName, String fileUrl, Integer profileId) {
        super(ProfileImageFile.PROFILE_IMAGE_FILE);

        set(0, id);
        set(1, fileName);
        set(2, fileUrl);
        set(3, profileId);
    }
}
