/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -2041387459;

    /**
     * Setter for <code>magpie.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.user.account</code>.
     */
    public void setAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.user.account</code>.
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.user.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.user.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.user.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.user.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>magpie.user.pasword</code>.
     */
    public void setPasword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.user.pasword</code>.
     */
    public String getPasword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>magpie.user.profile</code>.
     */
    public void setProfile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>magpie.user.profile</code>.
     */
    public String getProfile() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.ACCOUNT;
    }

    @Override
    public Field<String> field3() {
        return User.USER.COUNTRY_CODE;
    }

    @Override
    public Field<String> field4() {
        return User.USER.NAME;
    }

    @Override
    public Field<String> field5() {
        return User.USER.PASWORD;
    }

    @Override
    public Field<String> field6() {
        return User.USER.PROFILE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAccount();
    }

    @Override
    public String component3() {
        return getCountryCode();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getPasword();
    }

    @Override
    public String component6() {
        return getProfile();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAccount();
    }

    @Override
    public String value3() {
        return getCountryCode();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getPasword();
    }

    @Override
    public String value6() {
        return getProfile();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setAccount(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setPasword(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setProfile(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String account, String countryCode, String name, String pasword, String profile) {
        super(User.USER);

        set(0, id);
        set(1, account);
        set(2, countryCode);
        set(3, name);
        set(4, pasword);
        set(5, profile);
    }
}
