/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<Integer, String, String, String, Integer, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 977174924;

    /**
     * Setter for <code>magpie.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.user.account</code>.
     */
    public void setAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.user.account</code>.
     */
    public String getAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>magpie.user.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.user.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>magpie.user.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>magpie.user.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>magpie.user.pasword</code>.
     */
    public void setPasword(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>magpie.user.pasword</code>.
     */
    public Integer getPasword() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>magpie.user.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>magpie.user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>magpie.user.language</code>.
     */
    public void setLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>magpie.user.language</code>.
     */
    public String getLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>magpie.user.password</code>.
     */
    public void setPassword(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>magpie.user.password</code>.
     */
    public Integer getPassword() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>magpie.user.profile_id</code>.
     */
    public void setProfileId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>magpie.user.profile_id</code>.
     */
    public Integer getProfileId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>magpie.user.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>magpie.user.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.ACCOUNT;
    }

    @Override
    public Field<String> field3() {
        return User.USER.COUNTRY_CODE;
    }

    @Override
    public Field<String> field4() {
        return User.USER.NAME;
    }

    @Override
    public Field<Integer> field5() {
        return User.USER.PASWORD;
    }

    @Override
    public Field<String> field6() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return User.USER.LANGUAGE;
    }

    @Override
    public Field<Integer> field8() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<Integer> field9() {
        return User.USER.PROFILE_ID;
    }

    @Override
    public Field<Integer> field10() {
        return User.USER.LOCATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAccount();
    }

    @Override
    public String component3() {
        return getCountryCode();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Integer component5() {
        return getPasword();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getLanguage();
    }

    @Override
    public Integer component8() {
        return getPassword();
    }

    @Override
    public Integer component9() {
        return getProfileId();
    }

    @Override
    public Integer component10() {
        return getLocationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAccount();
    }

    @Override
    public String value3() {
        return getCountryCode();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Integer value5() {
        return getPasword();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getLanguage();
    }

    @Override
    public Integer value8() {
        return getPassword();
    }

    @Override
    public Integer value9() {
        return getProfileId();
    }

    @Override
    public Integer value10() {
        return getLocationId();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setAccount(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setCountryCode(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value5(Integer value) {
        setPasword(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public UserRecord value8(Integer value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value9(Integer value) {
        setProfileId(value);
        return this;
    }

    @Override
    public UserRecord value10(Integer value) {
        setLocationId(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String account, String countryCode, String name, Integer pasword, String email, String language, Integer password, Integer profileId, Integer locationId) {
        super(User.USER);

        set(0, id);
        set(1, account);
        set(2, countryCode);
        set(3, name);
        set(4, pasword);
        set(5, email);
        set(6, language);
        set(7, password);
        set(8, profileId);
        set(9, locationId);
    }
}
