/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq.tables.records;


import com.magpie.jooq.tables.Watch;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatchRecord extends UpdatableRecordImpl<WatchRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 136354558;

    /**
     * Setter for <code>magpie.watch.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>magpie.watch.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>magpie.watch.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>magpie.watch.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>magpie.watch.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>magpie.watch.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Watch.WATCH.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Watch.WATCH.ITEM_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Watch.WATCH.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getItemId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getItemId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public WatchRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WatchRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    @Override
    public WatchRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public WatchRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchRecord
     */
    public WatchRecord() {
        super(Watch.WATCH);
    }

    /**
     * Create a detached, initialised WatchRecord
     */
    public WatchRecord(Integer id, Integer itemId, Integer userId) {
        super(Watch.WATCH);

        set(0, id);
        set(1, itemId);
        set(2, userId);
    }
}
