/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq;


import com.magpie.jooq.tables.Country;
import com.magpie.jooq.tables.Product;
import com.magpie.jooq.tables.TestDummy;
import com.magpie.jooq.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Magpie extends SchemaImpl {

    private static final long serialVersionUID = 1194549189;

    /**
     * The reference instance of <code>magpie</code>
     */
    public static final Magpie MAGPIE = new Magpie();

    /**
     * The table <code>magpie.TEST_DUMMY</code>.
     */
    public final TestDummy TEST_DUMMY = com.magpie.jooq.tables.TestDummy.TEST_DUMMY;

    /**
     * The table <code>magpie.country</code>.
     */
    public final Country COUNTRY = com.magpie.jooq.tables.Country.COUNTRY;

    /**
     * The table <code>magpie.product</code>.
     */
    public final Product PRODUCT = com.magpie.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>magpie.user</code>.
     */
    public final User USER = com.magpie.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Magpie() {
        super("magpie", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TestDummy.TEST_DUMMY,
            Country.COUNTRY,
            Product.PRODUCT,
            User.USER);
    }
}
