/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq;


import com.magpie.jooq.tables.Category;
import com.magpie.jooq.tables.CategoryLevel;
import com.magpie.jooq.tables.Country;
import com.magpie.jooq.tables.ImageFile;
import com.magpie.jooq.tables.Item;
import com.magpie.jooq.tables.Location;
import com.magpie.jooq.tables.Message;
import com.magpie.jooq.tables.Product;
import com.magpie.jooq.tables.ProfileImageFile;
import com.magpie.jooq.tables.TestDummy;
import com.magpie.jooq.tables.User;
import com.magpie.jooq.tables.Watch;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Magpie extends SchemaImpl {

    private static final long serialVersionUID = 1899626135;

    /**
     * The reference instance of <code>magpie</code>
     */
    public static final Magpie MAGPIE = new Magpie();

    /**
     * The table <code>magpie.TEST_DUMMY</code>.
     */
    public final TestDummy TEST_DUMMY = com.magpie.jooq.tables.TestDummy.TEST_DUMMY;

    /**
     * The table <code>magpie.category</code>.
     */
    public final Category CATEGORY = com.magpie.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>magpie.category_level</code>.
     */
    public final CategoryLevel CATEGORY_LEVEL = com.magpie.jooq.tables.CategoryLevel.CATEGORY_LEVEL;

    /**
     * The table <code>magpie.country</code>.
     */
    public final Country COUNTRY = com.magpie.jooq.tables.Country.COUNTRY;

    /**
     * The table <code>magpie.image_file</code>.
     */
    public final ImageFile IMAGE_FILE = com.magpie.jooq.tables.ImageFile.IMAGE_FILE;

    /**
     * The table <code>magpie.item</code>.
     */
    public final Item ITEM = com.magpie.jooq.tables.Item.ITEM;

    /**
     * The table <code>magpie.location</code>.
     */
    public final Location LOCATION = com.magpie.jooq.tables.Location.LOCATION;

    /**
     * The table <code>magpie.message</code>.
     */
    public final Message MESSAGE = com.magpie.jooq.tables.Message.MESSAGE;

    /**
     * The table <code>magpie.product</code>.
     */
    public final Product PRODUCT = com.magpie.jooq.tables.Product.PRODUCT;

    /**
     * The table <code>magpie.profile_image_file</code>.
     */
    public final ProfileImageFile PROFILE_IMAGE_FILE = com.magpie.jooq.tables.ProfileImageFile.PROFILE_IMAGE_FILE;

    /**
     * The table <code>magpie.user</code>.
     */
    public final User USER = com.magpie.jooq.tables.User.USER;

    /**
     * The table <code>magpie.watch</code>.
     */
    public final Watch WATCH = com.magpie.jooq.tables.Watch.WATCH;

    /**
     * No further instances allowed
     */
    private Magpie() {
        super("magpie", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TestDummy.TEST_DUMMY,
            Category.CATEGORY,
            CategoryLevel.CATEGORY_LEVEL,
            Country.COUNTRY,
            ImageFile.IMAGE_FILE,
            Item.ITEM,
            Location.LOCATION,
            Message.MESSAGE,
            Product.PRODUCT,
            ProfileImageFile.PROFILE_IMAGE_FILE,
            User.USER,
            Watch.WATCH);
    }
}
