/*
 * This file is generated by jOOQ.
 */
package com.magpie.jooq;


import com.magpie.jooq.tables.TestDummy;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in magpie
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>magpie.TEST_DUMMY</code>.
     */
    public static final TestDummy TEST_DUMMY = TestDummy.TEST_DUMMY;
}
